# Generated by Django 4.1.4 on 2023-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_rename_user_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новости')], default='news', max_length=7),
        ),
    ]
